package com.nshaddox.randomtask.data.local

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room database entity representing a subtask belonging to a parent [TaskEntity].
 *
 * @property id Unique identifier, auto-generated by Room.
 * @property parentTaskId The id of the parent task. Foreign key with CASCADE delete.
 * @property title Short name or summary of the subtask.
 * @property isCompleted Whether the subtask has been marked as done.
 * @property createdAt Epoch milliseconds when the subtask was created.
 * @property updatedAt Epoch milliseconds when the subtask was last modified.
 */
@Entity(
    tableName = "subtasks",
    foreignKeys = [
        ForeignKey(
            entity = TaskEntity::class,
            parentColumns = ["id"],
            childColumns = ["parent_task_id"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [Index(value = ["parent_task_id"])],
)
data class SubTaskEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    @ColumnInfo(name = "parent_task_id") val parentTaskId: Long,
    @ColumnInfo(name = "title") val title: String,
    @ColumnInfo(name = "is_completed") val isCompleted: Boolean = false,
    @ColumnInfo(name = "created_at") val createdAt: Long,
    @ColumnInfo(name = "updated_at") val updatedAt: Long,
)
