package com.nshaddox.randomtask.data.local

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room database entity representing a task.
 *
 * @property id Unique identifier, auto-generated by Room.
 * @property title Short name or summary of the task.
 * @property description Optional longer description of the task. Null when not provided.
 * @property isCompleted Whether the task has been marked as done.
 * @property createdAt Epoch milliseconds when the task was created.
 * @property updatedAt Epoch milliseconds when the task was last modified.
 * @property priority The priority level stored as the enum name string. Defaults to "MEDIUM".
 * @property dueDate Optional due date stored as epoch days (days since 1970-01-01). Null when not set.
 * @property category Optional category label for grouping tasks. Null when not set.
 */
@Entity(tableName = "tasks")
data class TaskEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    @ColumnInfo(name = "title") val title: String,
    @ColumnInfo(name = "description") val description: String? = null,
    @ColumnInfo(name = "is_completed") val isCompleted: Boolean = false,
    @ColumnInfo(name = "created_at") val createdAt: Long,
    @ColumnInfo(name = "updated_at") val updatedAt: Long,
    @ColumnInfo(name = "priority") val priority: String = "MEDIUM",
    @ColumnInfo(name = "due_date") val dueDate: Long? = null,
    @ColumnInfo(name = "category") val category: String? = null,
)
